version: '3.1'
services:
  fluxdb:
    image: postgres
    networks:
      - flux-network
    volumes:
      - postgres-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=flux_db
      - POSTGRES_USER=flux
      - POSTGRES_PASSWORD=flux
    ports:
      - 5402:5432
    container_name: 'database-flux'
    restart: always
  flux-api:
    build: .
    networks:
      - flux-network
    environment:
      - DATABASE_URL=postgresql://flux:flux@fluxdb:5432/flux_db
      - JWT_SECRET=secrett
    ports:
      - 3000:3000
    depends_on:
      - fluxdb
    restart: always

volumes:
  postgres-data:
networks:
  flux-network:
    driver: bridge
